name: Build & lint project
on: [push, pull_request]

jobs:
  test:
    name: Pretest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: yarn

      - name: Copy config file
        run: cp example.config.ts config.ts

      - name: Install dependencies
        run: yarn install --immutable

      - name: Prebuild
        run: yarn build

  lint:
    name: ESLint type check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run ESLint
        run: yarn lint --fix

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style(eslint): Fixed eslint style format"
  build:
    name: Build and publish project
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: yarn

      - name: Copy config file
        run: cp example.config.ts config.ts
        
      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Remove fake config.js
        run: rm build/config.js

      - name: Copy .gitignore file
        run: cp .gitignore build/
        
      - name: Deploy with gh-pages
        if: ${{ github.ref_name == 'master' }}
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d build -b "build" -m "build: Hosting build for branch ${GITHUB_REF##*/} - ${GITHUB_SHA::7}" -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: buildData
          path: build